services:
  sb_app:
    container_name: spring-boot-api-bkool
    image: spring-boot-api-bkool
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/bikes
      - DATABASE_USERNAME=bryan
      - DATABASE_PASSWORD=root
    depends_on:
      - db

  db:
    container_name: postgres-bkool
    image: postgres
    environment:
      POSTGRES_USER: bryan
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  db: